# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102DOrQwLZlrCqERUEZnr2jjzivXCaL8Q
"""

!pip install librosa

import librosa as lb
import numpy as np
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]
genre_profiles = {
    "classical": {
        "tempo": (50, 120),
        "centroid": (300, 2000),
        "chroma_complexity": (0.10, 0.25),
    },
    "rock": {
        "tempo": (110, 170),
        "centroid": (2000, 6000),
        "chroma_complexity": (0.05, 0.12),
    },
    "edm": {
        "tempo": (120, 150),
        "centroid": (2500, 7000),
        "chroma_complexity": (0.02, 0.08),
    },
    "hiphop": {
        "tempo": (80, 115),
        "centroid": (300, 2500),
        "chroma_complexity": (0.04, 0.4),
    },
    "jazz": {
        "tempo": (90, 160),
        "centroid": (800, 3500),
        "chroma_complexity": (0.12, 0.30),
    },
    "pop": {
        "tempo": (90, 130),
        "centroid": (1500, 4000),
        "chroma_complexity": (0.03, 0.09),
    },
    "metal": {
        "tempo": (130, 200),
        "centroid": (3500, 8000),
        "chroma_complexity": (0.04, 0.10),
    },
    "ambient": {
        "tempo": (60, 100),
        "centroid": (200, 1500),
        "chroma_complexity": (0.01, 0.05),
    },
}

class Music:

    def __init__(self, path):
        self.path = path

    def temp(self):
        self.y, self.sr = lb.load(self.path, mono=True)
        self.tempo, _ = lb.beat.beat_track(y=self.y, sr=self.sr)
        return self.tempo
    def spectre(self):
        self.spectr = lb.feature.spectral_centroid(y=self.y, sr=self.sr)[0]
        return np.mean(self.spectr)
    def chtome(self):
        harmonic, percussive = lb.effects.hpss(self.y)
        self.chroma = lb.feature.chroma_stft(y=harmonic, sr=self.sr)
        return self.chroma

    def features(self):
        self.chroma_complexity = np.mean(np.std(self.chroma, axis=1))
        return {
            "tempo": self.tempo,
            "centroid": np.mean(self.spectr),
            "chroma_complexity": self.chroma_complexity,
        }
    def guess_genre(self):
      features = self.features()

      tempo = features["tempo"]
      centroid = features["centroid"]
      chroma_complexity = features["chroma_complexity"]

      best_genre = "unknown"
      best_score = -1

      for genre, prof in genre_profiles.items():
          score = 0
          t_min, t_max = prof["tempo"]
          c_min, c_max = prof["centroid"]
          сo_min, co_max = prof['chroma_complexity']
          if t_min <= tempo <= t_max:
              score += 1
          if c_min <= centroid <= c_max:
              score += 1
          if сo_min <= chroma_complexity <= co_max:
              score += 1

          if score > best_score:
              best_score = score
              best_genre = genre

      return best_genre



track = Music(filename)
track.temp()
track.spectre()
track.chtome()
track.features()
print(track.guess_genre())

